In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Introduction to tensors:**


In [2]:
scalar = torch.tensor(7)

# get sweet gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = scalar.to(device)
tensor_on_gpu

tensor(7, device='cuda:0')

In [3]:
scalar.item() # gives us our tensor back as integer
scalar.shape

torch.Size([])

In [4]:
vector = torch.tensor([1, 6, 2, 5])
vector.ndim
vector.shape

torch.Size([4])

In [5]:
matrix = torch.tensor([[7,8], [9,10]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [6]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]
    ]])

In [7]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random?
the way neural net's learn is by starting with tensors full of random numbers and adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random nums -> look at data -> update -> repeat `



In [8]:
# size (3, 4)

random_tensor = torch.rand(3, 6, 9)
print(random_tensor)

tensor([[[0.7995, 0.4603, 0.4138, 0.9481, 0.1855, 0.4619, 0.2160, 0.8714,
          0.0409],
         [0.0165, 0.5544, 0.8044, 0.7371, 0.3276, 0.5903, 0.3693, 0.1396,
          0.9677],
         [0.0378, 0.5177, 0.8325, 0.7865, 0.9132, 0.2504, 0.7916, 0.3817,
          0.6598],
         [0.1804, 0.5175, 0.2244, 0.7595, 0.2728, 0.4557, 0.4856, 0.4233,
          0.3800],
         [0.7304, 0.6821, 0.4256, 0.7594, 0.1080, 0.9804, 0.7094, 0.3413,
          0.2098],
         [0.6100, 0.9507, 0.6814, 0.0604, 0.2238, 0.6728, 0.3279, 0.2701,
          0.3716]],

        [[0.7287, 0.6550, 0.4165, 0.6672, 0.2572, 0.7567, 0.4422, 0.4906,
          0.5416],
         [0.3326, 0.2189, 0.1748, 0.0206, 0.8787, 0.7086, 0.9847, 0.2602,
          0.4988],
         [0.9281, 0.9327, 0.5095, 0.3885, 0.1271, 0.9644, 0.5521, 0.6302,
          0.9220],
         [0.1504, 0.4411, 0.1233, 0.5315, 0.5102, 0.3524, 0.3733, 0.7605,
          0.8845],
         [0.2554, 0.6332, 0.1960, 0.9621, 0.3131, 0.8649, 0.9194, 0.

In [9]:
random_tensor.ndim

3

In [10]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(rgb)
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [11]:
## Zeros and Ones
# Create a tensor of all zero's or all one's

zero_tensor = torch.zeros(size=(1, 3,5))
print(zero_tensor)

ones = torch.ones(size=(3,5))
ones
ones.dtype # starts off as float32 data type

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


torch.float32

### Create a range of tensors and tensors-like

In [12]:
zero_to_nine = torch.arange(0,10)
print(zero_to_nine)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
torch.arange(start=1,end=11,step=2)

tensor([1, 3, 5, 7, 9])

In [14]:
ten_zeros = torch.zeros_like(zero_to_nine)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### TENSOR DATATYPE

In [15]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
print(float_32_tensor.dtype) #default type is f32 even with none ^

torch.float32


### 3 COMMON ERRORS YOU'LL RUN INTO WITH TENSORS ARE:
1. Tensor Data Type
2. Tensor Shape
3. Tensor Device (cpu, cuda[0], etc)

In [16]:
float_16_tensor = float_32_tensor.type(torch.half)

In [17]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### GETTING INFORMATION FROM TENSORS

In [18]:
# to get dtype:
float_32_tensor.dtype

# to get shape:
float_32_tensor.shape

# to get device
float_32_tensor.device

device(type='cpu')

In [19]:
some_tensor = torch.rand(3,4)

# find details
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


### MANIUPLATING TENSORS (Tensor Operations)

# Tensor operations include:
  *Addition
  *Subtraction
  *Multiplication ( element-wise )
  *Division
  *Matrix Multiplication

  These are useful in creating information to represent a dataset

In [20]:
tens = torch.tensor([1,2,3])
tens+=100 # add 100 to it 
tens-= 20 # subtract 20
print(tens)

tensor([81, 82, 83])


In [21]:
tens*20 # multiply by 20 
torch.mul(tens, 20)

tensor([1620, 1640, 1660])

In [22]:
tens/.5

tensor([162., 164., 166.])

### MATRIX MULTIPLICATION
aka dot product ( a @ b )




One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

    The inner dimensions must match:
        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
    The resulting matrix has the shape of the outer dimensions:
        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)


In [23]:
tensOne = torch.tensor([1,2,3])
print (tensOne * tensOne) # normal element wise multiplication (1*1, 2*2, 3*3) = [1,4,9]
print(torch.matmul(tensOne, tensOne)) # Matrix multiplication (1*1+2*2+3*3)=[14]

tensor([1, 4, 9])
tensor(14)


Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:
Method 	One-line description
torch.reshape(input, shape) 	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
torch.Tensor.view(shape) 	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
torch.stack(tensors, dim=0) 	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
torch.squeeze(input) 	Squeezes input to remove all the dimenions with value 1.
torch.unsqueeze(input, dim) 	Returns input with a dimension value of 1 added at dim.
torch.permute(input, dims) 	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Now let's add an extra dimension with torch.reshape().

# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

We can also change the view with torch.view().

# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])

You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])



###Accessing a GPU with Torch


Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our device agnostic code (see above), it'll run on the CP



In [27]:
torch.cuda.is_available()

True

In [28]:


# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

torch.cuda.device_count() # zero-indexed [0, 1]

1

In [29]:
tense = torch.tensor([1,2,3])
print(tense, tense.device)

tense_on_gpu = tense.to(device)
print(tense_on_gpu, tense_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [30]:
exTensor = torch.rand(7,7)
print(exTensor)

tensor([[0.9389, 0.1798, 0.9221, 0.4025, 0.1268, 0.5854, 0.6696],
        [0.5172, 0.1486, 0.7871, 0.2225, 0.9269, 0.0160, 0.8821],
        [0.9286, 0.1495, 0.1741, 0.1515, 0.0017, 0.2632, 0.0269],
        [0.6783, 0.8492, 0.8549, 0.9966, 0.9281, 0.3619, 0.8206],
        [0.9272, 0.8525, 0.4133, 0.9734, 0.2275, 0.5086, 0.0081],
        [0.8205, 0.5709, 0.1845, 0.7421, 0.1250, 0.6687, 0.1192],
        [0.0024, 0.1472, 0.7074, 0.8776, 0.7262, 0.2303, 0.6384]])


In [31]:
anotherRand = torch.rand(1, 7)
print(anotherRand)

tensor([[0.9773, 0.8370, 0.9820, 0.2923, 0.0528, 0.7343, 0.5762]])


In [35]:
print(anotherRand.T.shape)
print(exTensor.shape) # both inner dimensions must be same (7, 7) @ (7, 1)
torch.matmul(exTensor, anotherRand.T)

torch.Size([7, 1])
torch.Size([7, 7])


tensor([[2.9135],
        [2.0367],
        [1.4567],
        [3.2921],
        [2.7002],
        [2.2440],
        [1.6520]])