In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Introduction to tensors:**


In [10]:
scalar = torch.tensor(7)

# get sweet gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = scalar.to(device)
tensor_on_gpu

tensor(7, device='cuda:0')

In [26]:
scalar.item() # gives us our tensor back as integer
scalar.shape

torch.Size([])

In [21]:
vector = torch.tensor([1, 6, 2, 5])
vector.ndim
vector.shape

torch.Size([4])

In [24]:
matrix = torch.tensor([[7,8], [9,10]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [27]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]
    ]])

In [32]:
TENSOR.ndim
TENSOR.shape

<function Tensor.size>

### Random Tensors

why random?
the way neural net's learn is by starting with tensors full of random numbers and adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random nums -> look at data -> update -> repeat `



In [41]:
# size (3, 4)

random_tensor = torch.rand(3, 6, 9)
print(random_tensor)

tensor([[[0.6970, 0.1458, 0.0274, 0.5070, 0.7855, 0.7794, 0.2767, 0.6376,
          0.9250],
         [0.1439, 0.7076, 0.8102, 0.2094, 0.0205, 0.3189, 0.0036, 0.0603,
          0.4935],
         [0.1923, 0.7078, 0.5722, 0.5690, 0.9514, 0.0528, 0.9857, 0.7262,
          0.2543],
         [0.5459, 0.2856, 0.2903, 0.5943, 0.1614, 0.9683, 0.0218, 0.9928,
          0.6162],
         [0.5504, 0.4204, 0.1563, 0.6557, 0.2836, 0.7900, 0.5133, 0.4328,
          0.4759],
         [0.8338, 0.2768, 0.8981, 0.2420, 0.6307, 0.7967, 0.5072, 0.9223,
          0.3239]],

        [[0.7924, 0.5354, 0.9670, 0.8450, 0.1459, 0.1498, 0.9371, 0.3529,
          0.2874],
         [0.9408, 0.7994, 0.1171, 0.9978, 0.0205, 0.4454, 0.1277, 0.2337,
          0.1579],
         [0.9106, 0.0665, 0.3662, 0.6438, 0.4150, 0.2401, 0.6937, 0.0200,
          0.5249],
         [0.6474, 0.5631, 0.7867, 0.6084, 0.1697, 0.8687, 0.8374, 0.4505,
          0.4524],
         [0.0121, 0.3653, 0.7918, 0.3739, 0.3741, 0.4628, 0.8333, 0.

In [36]:
random_tensor.ndim

2

In [40]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(rgb)
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [46]:
## Zeros and Ones
# Create a tensor of all zero's or all one's

zero_tensor = torch.zeros(size=(1, 3,5))
print(zero_tensor)

ones = torch.ones(size=(3,5))
ones
ones.dtype # starts off as float32 data type

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


torch.float32

### Create a range of tensors and tensors-like

In [57]:
zero_to_nine = torch.arange(0,10)
print(zero_to_nine)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [55]:
torch.arange(start=1,end=11,step=2)

tensor([1, 3, 5, 7, 9])

In [58]:
ten_zeros = torch.zeros_like(zero_to_nine)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### TENSOR DATATYPE

In [60]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
print(float_32_tensor.dtype) #default type is f32 even with none ^

torch.float32


### 3 COMMON ERRORS YOU'LL RUN INTO WITH TENSORS ARE:
1. Tensor Data Type
2. Tensor Shape
3. Tensor Device (cpu, cuda[0], etc)

In [61]:
float_16_tensor = float_32_tensor.type(torch.half)

In [62]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### GETTING INFORMATION FROM TENSORS

In [63]:
# to get dtype:
float_32_tensor.dtype

# to get shape:
float_32_tensor.shape

# to get device
float_32_tensor.device

device(type='cpu')

In [65]:
some_tensor = torch.rand(3,4)

# find details
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


### MANIUPLATING TENSORS (Tensor Operations)

# Tensor operations include:
  *Addition
  *Subtraction
  *Multiplication ( element-wise )
  *Division
  *Matrix Multiplication

  These are useful in creating information to represent a dataset

In [71]:
tens = torch.tensor([1,2,3])
tens+=100 # add 100 to it 
tens-= 20 # subtract 20
print(tens)

tensor([81, 82, 83])


In [72]:
tens*20 # multiply by 20 
torch.mul(tens, 20)

tensor([1620, 1640, 1660])

In [73]:
tens/.5

tensor([162., 164., 166.])

### MATRIX MULTIPLICATION
aka dot product ( a @ b )




One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

    The inner dimensions must match:
        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
    The resulting matrix has the shape of the outer dimensions:
        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)


In [76]:
tensOne = torch.tensor([1,2,3])
print (tensOne * tensOne) # normal element wise multiplication (1*1, 2*2, 3*3) = [1,4,9]
print(torch.matmul(tensOne, tensOne)) # Matrix multiplication (1*1+2*2+3*3)=[14]

tensor([1, 4, 9])
tensor(14)
